#!/bin/bash

# emulate workdir usage
echo "some id" > .hw-agent-id 
mkdir .hw-cache
echo "some cache data" > .hw-cache/cacheFile1

while true; do
    echo "Simulate a process message"
    sleep 1
done
