#!/bin/sh
set -e

case "$1" in
    configure)
        if [ ! -d "/var/log/heisenware" ];
        then
            echo "postinst creating /var/log/heisenware directory"
            mkdir -p /var/log/heisenware
        fi

        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "postinst updating {SERVICE_NAME} unit"
            deb-systemd-helper update-state '{SERVICE_NAME}.service'
        fi

        if ! deb-systemd-helper --quiet is-enabled '{SERVICE_NAME}.service';
        then
            echo "postinst enabling {SERVICE_NAME} unit"
            # Ubuntu does not work well with deb-systemd-helper enable
            systemctl enable '{SERVICE_NAME}.service'
            deb-systemd-invoke --system daemon-reload
        fi

        echo "postinst starting {SERVICE_NAME} unit"
        deb-systemd-invoke start '{SERVICE_NAME}.service'
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "postinst restarting original {SERVICE_NAME} unit"
            deb-systemd-invoke --system daemon-reload
            deb-systemd-invoke restart '{SERVICE_NAME}.service'
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
