#!/bin/sh
set -e

case "$1" in
    configure)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "postinst updating {SERVICE_NAME} unit"
            deb-systemd-helper update-state '{SERVICE_NAME}.service'
        fi

        if [ ! $(deb-systemd-helper --quiet is-enabled '{SERVICE_NAME}.service') ];
        then
            echo "postinst enabling {SERVICE_NAME} unit"
            systemctl enable '{SERVICE_NAME}.service'
        fi

        echo "postinst starting {SERVICE_NAME} unit"
        systemctl start '{SERVICE_NAME}.service'
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "postinst restarting original {SERVICE_NAME} unit"
            systemctl --system daemon-reload
            systemctl restart '{SERVICE_NAME}.service'
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
