#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if ! command -v logrotate > /dev/null 2>&1; 
        then
            echo "Error: logrotate is not installed."
            exit 1
        fi

        if systemctl is-active --quiet '{SERVICE_NAME}.service'; 
        then
            echo "preinst stopping {SERVICE_NAME} unit"
            deb-systemd-invoke stop '{SERVICE_NAME}.service'
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

