#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if systemctl is-active --quiet '{SERVICE_NAME}.service'; then
            echo "preinst stopping {SERVICE_NAME} unit"
            deb-systemd-invoke stop '{SERVICE_NAME}.service'
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

