#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}';
        then
            echo "prerm stopping {SERVICE_NAME} unit"
            deb-systemd-invoke stop '{SERVICE_NAME}'
        fi
    ;;

    failed-upgrade)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}';
        then
            echo "prerm restarting original {SERVICE_NAME} unit"
            systemctl --system daemon-reload
            deb-systemd-invoke restart '{SERVICE_NAME}'
        fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
