#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "prerm stopping {SERVICE_NAME} unit"
            systemctl stop '{SERVICE_NAME}.service'
        fi
    ;;

    failed-upgrade)
        if deb-systemd-helper --quiet was-enabled '{SERVICE_NAME}.service';
        then
            echo "prerm restarting original {SERVICE_NAME} unit"
            systemctl --system daemon-reload
            systemctl restart '{SERVICE_NAME}.service'
        fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
